export const genderFilter = [
    {value: 0, label: "Male"},
    {value: 1, label: "Female"}
]

export const noteFilter = [
    {value: 0, label: "A0"},
    {value: 1, label: "A#0"},
    {value: 2, label: "B0"},
    {value: 3, label: "C1"},
    {value: 4, label: "C#1"},
    {value: 5, label: "D1"},
    {value: 6, label: "D#1"},
    {value: 7, label: "E1"},
    {value: 8, label: "F1"},
    {value: 9, label: "F#1"},
    {value: 10, label: "G1"},
    {value: 11, label: "G#1"},
    {value: 12, label: "A1"},
    {value: 13, label: "A#1"},
    {value: 14, label: "B1"},
    {value: 15, label: "C2"},
    {value: 16, label: "C#2"},
    {value: 17, label: "D2"},
    {value: 18, label: "D#2"},
    {value: 19, label: "E2"},
    {value: 20, label: "F2"},
    {value: 21, label: "F#2"},
    {value: 22, label: "G2"},
    {value: 23, label: "G#2"},
    {value: 24, label: "A2"},
    {value: 25, label: "A#2"},
    {value: 26, label: "B2"},
    {value: 27, label: "C3"},
    {value: 28, label: "C#3"},
    {value: 29, label: "D3"},
    {value: 30, label: "D#3"},
    {value: 31, label: "E3"},
    {value: 32, label: "F3"},
    {value: 33, label: "F#3"},
    {value: 34, label: "G3"},
    {value: 35, label: "G#3"},
    {value: 36, label: "A3"},
    {value: 37, label: "A#3"},
    {value: 38, label: "B3"},
    {value: 39, label: "C4"},
    {value: 40, label: "C#4"},
    {value: 41, label: "D4"},
    {value: 42, label: "D#4"},
    {value: 43, label: "E4"},
    {value: 44, label: "F4"},
    {value: 45, label: "F#4"},
    {value: 46, label: "G4"},
    {value: 47, label: "G#4"},
    {value: 48 , label: "A4"},
    {value: 49	, label: "A#4"},
    {value: 50	, label: "B4"},
    {value: 51	, label: "C5"},
    {value: 52	, label: "C#5"},
    {value: 53	, label: "D5"},
    {value: 54	, label: "D#5"},
    {value: 55	, label: "E5"},
    {value: 56	, label: "F5"},
    {value: 57	, label: "F#5"},
    {value: 58	, label: "G5"},
    {value: 59	, label: "G#5"},
    {value: 60	, label: "A5"},
    {value: 61	, label: "A#5"},
    {value: 62	, label: "B5"},
    {value: 63	, label: "C6"},
    {value: 64	, label: "C#6"},
    {value: 65	, label: "D6"},
    {value: 66	, label: "D#6"},
    {value: 67	, label: "E6"},
    {value: 68	, label: "F6"},
    {value: 69	, label: "F#6"},
    {value: 70	, label: "G6"},
    {value: 71	, label: "G#6"},
    {value: 72	, label: "A6"},
    {value: 73	, label: "A#6"},
    {value: 74	, label: "B6"},
    {value: 75	, label: "C7"},
    {value: 76	, label: "C#7"},
    {value: 77	, label: "D7"},
    {value: 78	, label: "D#7"},
    {value: 79	, label: "E7"},
    {value: 80	, label: "F7"},
    {value: 81	, label: "F#7"},
    {value: 82	, label: "G7"},
    {value: 83	, label: "G#7"},
    {value: 84	, label: "A7"},
    {value: 85	, label: "A#7"},
    {value: 86	, label: "B7"},
    {value: 87	, label: "C8"}
]