export const ADD_VOCALIST = 'ADD_VOCALIST';
export const ADD_TO_CHART = 'ADD_TO_CHART';
export const REMOVE_FROM_CHART = 'REMOVE_FROM_CHART';
export const POST_CHANGE = 'POST_CHANGE';
export const POPULATE_NAMES = 'POPULATE_NAMES';
export const POST_REMOVE_CHANGE = 'POST_REMOVE_CHANGE';