export const ADD_VOCALIST = 'ADD_VOCALIST';
export const GET_NAMES = 'GET_NAMES';
export const GET_GENDERS = 'GET_GENDERS';
export const GET_HIGHEST_NOTES = 'GET_HIGHEST_NOTES';
export const GET_LOWEST_NOTES = 'GET_LOWEST_NOTES';
export const POPULATE_NAMES = 'POPULATE_NAMES';